GET http://localhost:5000/api/movies HTTP/1.1

###
GET http://localhost:5000/api/movies/order HTTP/1.1

###
POST http://localhost:5000/api/movie/add HTTP/1.1
content-type: application/json

{
    "title":"Yüzüklerin Efendisi ve Kralın Dönüşü",
    "author":"Peter Jackson",
    "watched":true,
    "addedBy":"Cemal Can İŞÇİ",
    "order":2,
    "category":"Fantastik"
}

###

PUT http://localhost:5000/api/movie/change-status/5ebf0147fb4d8523844cf071 HTTP/1.1
content-type: application/json

{
    "watched":true
}

###

GET http://localhost:5000/api/category HTTP/1.1


###
POST http://localhost:5000/api/category HTTP/1.1
Content-Type: application/json

{
    "title":"Macera"
}